env: "local"
storage_path: "./storage"

http_server:
  address: "0.0.0.0:8081"
  timeout: 5s
  idle_timeout: 120s

analysis_server:
  address: "0.0.0.0:8069"
  timeout: 5s
  idle_timeout: 120s

storage_db:
  dsn: "postgres://gleboss:adminadmin@db:5432/antiplag_storage?sslmode=disable"

analysis_db:
  dsn: "postgres://gleboss:adminadmin@db:5432/antiplag_analysis?sslmode=disable"

gateway:
  storage_base_url: "http://storage:8081"
  analysis_base_url: "http://analysis:8069"
  address: "0.0.0.0:8052"
