env: "local"
storage_path: "./storage"

http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 120s

storage_db:
  dsn: "postgres://gleboss:adminadmin@localhost:5432/antiplag_storage?sslmode=disable"
